.Dd @nix-date@
.Dt DCURGZ.ME 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm Dylan Curzon
.Nd Software Engineer (he/him)
.
.Sh SYNOPSIS
.Nm github
.Lk https://github.com/dcurgz dcurgz
.
.Sh DESCRIPTION
I'm interested in Linux, Nix, AOSP, amongst other things.
This page is meant to host a technical blog in the near future. WIP!
.
.Pp
Here are some prospective posts that I am planning to write. Stay tuned: here's an
.Lk /rss.xml rss feed .
.Pp
My thoughts and posts here are my own and do not represent any current or former employer.
.
.Pp
This site was built on @nix-rfc822@ by
.Lk https://github.com/dcurgz/nix/blob/master/www/dcurgz.me/index.7 dcurgz/nix .
.El
