@include:header@
.
.Sh NAME
.Nm Dylan Curzon
.Nd Software Engineer (they/he)
.
.Sh ABOUT
You have arrived at dcurgz's personal website. I'm interested in:
.Bl
.It
NixOS
.It
AOSP (e.g GrapheneOS)
.It
Infrastructure, DevOps and CI/CD
.It
Decentralization and privacy
.It
Sustainability
.It
Security
.El
.Pp
Here's some posts I've written recently:
.Bl
.It
.Lk /posts/001_NixOS.html 001 NixOS
— How I'm using NixOS today (WIP!)
.El
.
.Sh LINKS
.Nm GitHub
.Nd
.Lk https://github.com/dcurgz @dcurgz
.Nm RSS
.Nd
.Lk /rss.xml /rss
.
.Sh CONTACT
.Pp
@include:email@
.
Thank you for visiting my website.
.
@include:build-time@
