@include:header@
.
.Sh NAME
.Nm Dylan Curzon
.Nd Software Engineer (they/he)
.
.Sh SYNPOSIS
Welcome to my technical blog. I'm interested in:
.Bl
.It
NixOS
.It
AOSP (e.g GrapheneOS)
.It
Infrastructure, DevOps and CI/CD
.It
Decentralization and privacy
.It
Sustainability
.It
Security
.El
.Pp
Here are some posts I've written recently:
.Bl
.It
.Lk /posts/001_NixOS.html 001 NixOS
— How I'm using NixOS today (WIP!)
.El
.
.Ss LINKS
.Nm GitHub
.Nd
.Lk https://github.com/dcurgz @dcurgz
.Nm RSS
.Nd
.Lk /rss.xml /rss
.
.Ss CONTACT
I'm hoping this blog will introduce me to all kinds of interesting people doing
interesting things. If you'd like to get in touch, my contact details are
below.
@include:contact@
.
Thank you for visiting my website.
.
@include:build-time@
