.Dd January 24, 2026
.Dt META:WHY 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm meta:why
.Nd An explanation for this website.
.Pp
.Em Note: This post is unpublished.
That means I'm still working on it.
.
.Sh DESCRIPTION
After a long time of planning to do it and putting it off, I've finally
committed to a domain name, the relevant infrastructure, and an overall
direction for my personal website.
.Pp
I've noticed, talking about it to friends, a recurring pattern of mild to
moderate confusion about why I would want a personal blog in the first place. I
understand that it's fairly unusual broadly, and even in my particular social
spheres, but I do find it ironic.
.Pp
I'm trying my best to avoid sounding bitter about this - I'm really
.Em not
bitter about it - but I notice that, at least from my generation, there's no
surprise associated with, say, posting on mainstream social media. Creating and
maintaining an active Instagram account that documents your life, for example,
is considered completely normal amongst my generation. In fact, I've noticed
quite a bit of friction getting to know people, especially in dating, as a
result of not using Instagram in this way. My best guess is that the disparity
in surprise is down to the prevalent normalization of social media usage today,
and some assumptions about what a personal blog is all about.
.Pp
Either way, I don't blame people for being confused about it, but it does mean
I feel the need to keep justifying its existence in partial or full form, so I
figured it would probably be best to just write something down. So, these are
(most) of the reasons why this website exists.
.Bl -enum -width Ds
.It 
.Em I'm hoping it will help give me clarity on topics that I care about.
.Pp
I have a bit of a problem with over-explaining myself. If you're a friend of
mine, you're probably aware of this already. As I understand it, this happens
for a few reasons, but largely it is because my head can be very messy. I'm
not very skilled in expressing myself in verbal language on the fly, so my
spoken thoughts in conversation can be incoherent, sometimes irrelevant, and
hard to follow.  As a result, I'm often left feeling unsatisifed and
misunderstood after trying to explain something that means a lot to me. My
theory is that by posting some of these ramblings here, in written form, I can
better come to understand my own thoughts, which can help me to explain myself
succinctly and precisely when I need to. In this light, this website will be
something of a public journal, focused on the topics that mean a lot to me.
.It
.Em It's a kind of self-expression.
.Pp
I think all people desire self-expression; it might be the only reason that we
are here at all, at least in an individual capacity. It's clear that this is no
different today than it ever was. Things like Instagram, TikTok, and Twitter
are omnipresent in our lives, and it is not down to pure chance that it is this
way; these kinds of Apps provide people with entertainment, a sense of
connection, and a platform for self-expression. It's easy to forget that this
flowery ideal is
.Em kind of the entire point
in a world constructed, brick by brick, by hidden forces, to keep us busy,
judging ourselves predominantly by our economic contribution and the quality of
our pointless possessions.
.Pp
Bitter cynacism aside, I've been feeling, day by day, more and more discontent
with the lack of self-expression in my life. I think that this is not a rare
feeling to have, though it might be rare to understand it; it seems that the
entire concept of a stereotypical man is one of quiet resignation from
expression of any kind.
.Pp
This website is my attempt at stepping into the limelight for a change. It's
not that I think that I am particularly important, clever or interesting - far
from it, though I'm quite sure some readers will choose to interpret the
writing of this site with an aura of self-importance regardless of what I
claim. But I think all people are owed the freedom to express themselves, be
heard and seen, and I've taken to allow myself that freedom as well.
.Pp
I know that this entire segment is, through and through, a testament of my
privileged life. I don't deny that it is a privilege to have the time to even
think about any of this, while some are wondering where their next meal will
be, or whether it will be their house that is striked next. I think, again, I
will be judged for this relentlessly by some no matter what I do. But it is my
philosophy that you must care for yourself before you can care for others.
This is me caring for myself, so that I may better help others.
.It
.Em I'm a huge fan of other people's technical blogs.
.Pp
Over the last three years I've learned so much from other people's technical
blogs. I've been having a lot of fun with NixOS recently; for example, this
entire website is
.Lk https://github.com/dcurgz/nix/blob/master/presets/www/weirdfi.sh/posts/why.7 "defined declaratively"
with Nix. I've been getting interested in things like sustainability in tech
.Sm off
.Lk https://example.com [0]
.Lk https://example.com [1]
.Lk https://example.com [2] ,
.Sm on
and projects like
.Lk https://example.com GrapheneOS
that have successfully reclaimed freedoms and privacy for its users from the
tech bethemoths that run our world. I've gained perspective on important,
relevant topics of today, such as the recent (largely, catastrophic)
introduction of generative AI into everyday life. If it weren't for niche
technical blogs, I might not have read into some of these things, and I would
be all the lesser for it. I've learned much more; things that I cannot
explicitly enumerate here, but I feel strongly have surely shifted my
perspective on the world in a profound
way.
.Pp
By technical blog, I'm predominantly referring to sites that talk about
technology e.g. system architecture, reverse engineering, and security
practices, but I've also found immense value in the writing of strangers on
their personal lives, problems they've faced and overcome, and their opinions
on various things. I don't really follow people on social media, so these niche
internet webpages have filled a huge gap in my life in terms of a sense of
connection with like minded people.
.Pp
I feel a considerable pull to join this community of people posting silly or
thoughtful pieces to an audience of friends and strangers; I want to give back
to the internet that which it has given me.
.Pp
.El
If anything, I think that it's not surprising that I've started a technical
blog, but rather, surprising that it's
.Em taken me so long.
TBC
.
.Sh SEE ALSO
.Bl -enum -width Ds
.El
.Sh HISTORY
.Bl -enum -width Ds
.It
.Sy 26/01/2026
- improved formatting, and extended with more points.
.It
.Sy 24/01/2026
- /posts/why.7 created.
