.Dd February 28, 2026
.Dt META:WHY 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm meta:why
.Nd my motivations behind this silly webpage.
.Sh DESCRIPTION
After a long time of planning to do it and putting it off, I've finally
committed to a domain name, the relevant infrastructure, and an overall
direction for my personal website.
.Pp
This post was going to be a long-form justification for why I've wanted to make
it. I rewrote it many times. I think it would be better to be brief.
.Pp
Firstly, I want a space where I can rant about silly tech things I'm doing,
such as over-engineering my homelab infrastructure i.e. NixOS. This could
include updates for my long-term open-source projects, which I have been
putting off for many millenia, but want to do at some point.
.Pp
Secondly, I'd like a place to put some pseudo-personal ramblings about things
that are on my mind. I get obsessed sometimes with finding the right way to
envision, abstract or put into words a given part of the world.
.Pp
I'm always thinking about how people work - things we take for granted, like
mental processes, or the parts of our minds that we identify with and why, or
how emotions and physiological needs are processed and come to influence our
decisions.
.Pp
It is funny to me, and maybe sad as well, how oftentimes people don't know
themselves at all. For the longest time, I barely knew myself, and that meant
that I hurt people I care about. I'm a bit better at it now. I think this
website will help with it.
.Pp
Finally, I might use this space to post writings of sorts. I've wanted to write
fiction for some years now. It will probably be sci-fi, and sad, and maybe
funny as well. I'm hoping that I will finally get around to it, now that there
is a place where it can live.
.Pp
That's it really. As an aside, I think it could be a nice way to meet cool
people. I've read some posts describing personal blogs as a kind of attractor,
bringing together folks that are doing interesting things, and think and feel
similarly to you. That sounds nice, even if I find it unlikely.
.Pp
If you're a human, and want to reach out, please feel free. Unfortunately, the
easiest way right now is via my Discord, @dylan.tar.gz. I don't love Discord
and I'd like to move away from it eventually. You can also email me at the
address given below.
.Pp
.Bd -literal -offset indent -compact
    #!/usr/bin/env bash
    echo "zr@phem.fu" | tr '[n-za-m]' '[a-z]'
.Ed
.Pp
Thank you for reading.
.Pp
~ dylan
.Pp
p.s. it's probably obvious, but weirdfish(es) is a song by Radiohead. I like it
a lot.
