.Dd February 5, 2026
.Dt META:WHY 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm meta:why
.Nd An explanation for this website.
.Pp
.Em Note: This post is unpublished.
.
.Sh DESCRIPTION
After a long time of planning to do it and putting it off, I've finally
committed to a domain name, the relevant infrastructure, and an overall
direction for my personal website.
.Pp
I've noticed, talking about it to friends, a recurring pattern of mild to
moderate confusion about why I would want a personal blog in the first
place. I don't blame people for being confused about it, but it does mean I
feel the need to keep justifying its existence in partial or full form, so I
figured it would probably be best to just write something down. 
.Bl -enum -width Ds
.It 
.Em I'm hoping it will give me clarity.
.Pp
I have a bit of a problem with over-explaining myself. If you're a friend of
mine, you're probably aware of this already. As I understand it, this
happens for a few reasons, but largely it is because my head can be very
messy. As a result, I'm often left feeling unsatisifed and misunderstood
after trying to explain something that means a lot to me. My theory is that
by posting some of these ramblings here, in written form, I can better come
to understand my own thoughts, which can help me to explain myself
succinctly and precisely when I need to. In this light, this website will be
something of a public journal, focused on the topics that mean a lot to me.
.It
.Em It's a kind of self-expression.
.Pp
I think all people desire self-expression; it might be the only reason that
we are here at all, at least in an individual capacity. It's clear that this
is no different today than it ever was. Things like Instagram, TikTok, and
Twitter are omnipresent in our lives, and it is not down to pure chance that
it is this way; these kinds of Apps provide people with entertainment, a
sense of connection, and a platform for self-expression. It's easy to forget
that this flowery ideal is
.Em kind of the entire point
in a world constructed, brick by brick, by hidden forces, to keep us busy,
judging ourselves predominantly by our economic contribution and the quality of
our pointless possessions.
.Pp
It's been a long time since I put myself out there creatively. This is not
for lack of wanting; I have so many ideas that I want to express to the
world. I've been very distracted by the things that are carefully designed
to distract me, and willingly so; it was what I needed for a long while.
That said, I think it's time to stop that now, and focus for once on the
things that I want to do, say, and create. I think this website will keep me
focused on the creative ideas I have, help me see them through, and also be
a kind of self-expression on its own.
.It
.Em I have a debt to pay to the writers of the internet.
.Pp
It's hard to enumerate all of the things that I've learned, over the last three
years, reading blogs and pieces on the internet. There are a few big mentions,
for example that I've been using GrapheneOS[0] as my daily driver for several
years now, and I've spent a large part of the last year learning and utilizing
NixOS[1], which is what powers this website.
.Pp
Through reading, I've developed my opinions on a few things of note, such as
my distaste for tech molopolies and the large-scale, unapologetic
surveillance carried out by them and our governments, the closely related
ad-tech industry, and the gradually worsening trend of taking away the
rights and control of consumers over their own hardware. I've read a
thousand takes on Generative AI, some amazed, some unimpressed, some deeply
disturbed, and many that fall somewhere in between[3]. 
.Pp
Further, I've found a wide range of interesting ideas (many on the LessWrong[2]
front page), from analytical ethical deliberations that made me reframe many
interactions, to short stories that perfectly capture some of my feelings about
the capitalist, dystopian world that we quietly live within.
.Pp
I could go on with attempting to pick apart the views I've formed on things,
attributing them to various subcultures of internet writers, but I think this
would miss the point that I'm trying to make. The last few years have been
instrumental for me in developing my character and outlook on the world, and I
owe so much to niche blog posts, think pieces, technical writeups and public
journals for making me who I am. They kept me sane throughout tenuous,
soul-destroying, pointless work, and helped me to stay passionate about the
things that matter. 
.Pp
I feel a considerable pull to join this vast community of people posting silly
or thoughtful pieces to an audience of friends and strangers; I want to give
back to the internet that which it has given me. So, here goes nothing.
.Pp
.El
.Sh FOOTNOTES
.Bl -enum -width Ds
.It
[0]:
.Lk https://grapheneos.org/ GrapheneOS
is an alternative operating system for Android phones, with privacy features
that help mitigate the extensive spying from Google that comes baked in with
standard Android. Note that, unfortunately, they only support Google Pixel
phones, as they are the only device manufacturer with sufficient hardware
security at this time. The irony is not lost on them, believe me.
.It
[1]: 
.Lk https://nixos.org/ NixOS
is like, an operating system, or something like that. It's possible that this
website merely exists as an excuse to do, talk about, and rely on NixOS even
more. In any case, I'll probably make a few posts on it in the near future.
.It
[2]:
.Lk https://www.lesswrong.com/ LessWrong
is a message board for over-thinkers. It gets a lot of hate for
pseudo-intellectualism and AI doomer fear mongering, which it certainly does
feature, but I've still found a lot of interesting takes on it.
.It
[3]: I'll likely write something about the current wave of generative AI models
soon, but in a few words, I'll just say:
.Em we've fucked up.
.El
