.Dd @nix-date@
.Dt WEIRDFI.SH 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm weirdfi.sh
.Nd A personal blog.
.
.Sh DESCRIPTION
This is my blog, weirdfi.sh - home to incoherent, varied rambling on topics like NixOS, self-hosting, privacy, and personal melodrama. 
.
Welcome to my quarter life crisis, rendered in
.Lk https://man.openbsd.org/mdoc.7 mdoc(7)
format.
.
.Sh IMPLEMENTATION NOTES
This site was built on @nix-rfc822@ by
.Lk https://github.com/dcurgz/nix/blob/master/presets/www/weirdfi.sh/index.7 dcurgz/nix .
.Sh AUTHORS
.An dcurgz (dylan) - 
.Lk https://github.com/dcurgz github ,
.Lk https://bsky.app/weirdfi.sh bsky
.El
