.Dd @nix-date@
.Dt WEIRDFI.SH 7
.Os @nix-gitrev@
.
.Sh NAME
.Nm dcurgz
.Nd declarative goblin (he/they)
.
.Sh SYNOPSIS
.Nm github
.Lk https://github.com/dcurgz @dcurgz
.Nm bsky
.Lk https://bsky.app/profile/weirdfi.sh @weirdfi.sh
.
.Sh DESCRIPTION
welcome to my quarter life crisis, rendered in
.Lk https://man.openbsd.org/mdoc.7 mdoc(7)
format.
.
.Pp
This site was built on @nix-rfc822@ by
.Lk https://github.com/dcurgz/nix/blob/master/presets/www/weirdfi.sh/index.7 dcurgz/nix .
.El
